spring:
    application:
      name: nfc_service
    datasource:
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

upaiyun:
   bucketName: test-lyndon-hotel
   operatorName: lyndon
   operatorPwd: lyndon

qiniu:
   bucket: nfccardtest
   accessKey: VtHaqZVI7WzhWSCPXvtXQyBs2YeNwMwvAz7IP--7
   secretKey: 4GtcKQg6UthzxkFfWIw1NqmWVA7kFefJBAFjcc8x


mybatis:
    mapper-locations: classpath*:mappers/**/*.xml
    type-aliases-package: com.nfc.lyndon.nfcard.entity




